Repository SkyFlyTeam/cloudStock, pull requests merged in 2024-11, with the labels that each got.

#72 Feature/back notificacao
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/config/connection.ts
  backend/src/config/init.ts
  backend/src/config/validadeNotificacaoCron.ts
  backend/src/controllers/configController.ts
  backend/src/controllers/produtoController.ts
  backend/src/controllers/saidaController.ts
  backend/src/models/ConfigSistema.ts
  backend/src/models/Entrada.ts
  backend/src/models/Lote.ts
  backend/src/models/Notificacoes.ts
  backend/src/models/Produto.ts
  backend/src/models/Saida.ts
  backend/src/routes/configRoutes.ts
  backend/src/routes/index.ts
  frontend/src/components/Input/index.tsx
  frontend/src/pages/Entrada/index.tsx
  frontend/src/pages/Entrada/style.css
  frontend/src/pages/EntradasRegistro/index.tsx
  frontend/src/pages/EntradasRegistro/style.css
  frontend/src/pages/Saidas/index.tsx
  frontend/src/pages/Saidas_cadastro/index.tsx
  frontend/src/services/saidaServices.ts
Labels: enhancement

#73 Feature/filtros produtos
  backend/src/controllers/loteController.ts
  backend/src/models/Entrada.ts
  backend/src/models/Registros.ts
  backend/src/models/Saida.ts
  backend/src/routes/loteRoutes.ts
  frontend/src/pages/EntradasRegistro/index.tsx
  frontend/src/pages/EntradasRegistro/style.css
  frontend/src/pages/Fornecedores/index.tsx
  frontend/src/pages/Fornecedores/style.css
  frontend/src/pages/LocalProduto/index.tsx
  frontend/src/pages/LocalProduto/style.css
  frontend/src/pages/Produtos/index.tsx
  frontend/src/pages/Produtos/style.css
  frontend/src/pages/Registros/index.tsx
  frontend/src/pages/Registros/style.css
  frontend/src/pages/Saidas/index.tsx
  frontend/src/pages/Saidas/style.css
  frontend/src/services/entradaServices.ts
  frontend/src/services/produtoServices.ts
  frontend/src/services/registrosServices.ts
  frontend/src/services/saidaServices.ts
  frontend/src/services/usuariosServices.ts
Labels: enhancement, task, Rank 15

#78 Feature/paginacao
  frontend/src/components/Pagination/Pagination.css
  frontend/src/components/Pagination/index.tsx
  frontend/src/pages/Produtos/LoadingDots.tsx
  frontend/src/pages/Produtos/index.tsx
  frontend/src/pages/Produtos/style.css
  frontend/src/routes/routes.tsx
Labels: enhancement, Rank 15

#74 Feature/notificacoes offcanvas
  backend/package-lock.json
  backend/package.json
  backend/src/app.ts
  backend/src/config/connection.ts
  backend/src/config/validadeNotificacaoCron.ts
  backend/src/config/webSocket.ts
  backend/src/controllers/notificacoesController.ts
  backend/src/models/ConfigSistema.ts
  backend/src/models/Entrada.ts
  backend/src/models/Lote.ts
  backend/src/models/Notificacoes.ts
  backend/src/models/Produto.ts
  backend/src/models/Saida.ts
  backend/src/routes/configRoutes.ts
  backend/src/routes/index.ts
  backend/src/routes/notificacoesRoutes.ts
  frontend/src/assets/icons/Simplification.svg
  frontend/src/components/Barra Superior/BarraSuperior.css
  frontend/src/components/Barra Superior/index.tsx
  frontend/src/components/navbar/Navbar.css
  frontend/src/context/AuthProvider.tsx
  frontend/src/pages/Entrada/index.tsx
  frontend/src/pages/LocalProduto/index.tsx
  frontend/src/pages/LocalProduto/style.css
  frontend/src/pages/Registros/index.tsx
  frontend/src/routes/ProtectedRoute.tsx
  frontend/src/services/entradaServices.ts
  frontend/src/services/notificacoesServices.ts
  frontend/src/services/produtoServices.ts
  frontend/src/services/usuariosService.ts
  frontend/src/style/global.css
Labels: enhancement, task

#77 Feature/backend categorias
  backend/src/controllers/categoriaController.ts
  backend/src/controllers/produtoController.ts
  backend/src/models/Categoria.ts
  backend/src/routes/categoriaRoutes.ts
Labels: enhancement, Produto
